/*
 * Copyright 2026 Paul Griffioen
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package pacioli.documentation;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.Writer;
import java.util.ArrayList;
import java.util.List;

import pacioli.Pacioli;
import pacioli.ast.expression.ExpressionNode;
import pacioli.ast.expression.LambdaNode;
import pacioli.compiler.PacioliException;
import pacioli.compiler.PacioliFile;
import pacioli.compiler.Program;
import pacioli.symboltable.PacioliTable;
import pacioli.symboltable.info.ValueInfo;
import pacioli.types.ast.FunctionTypeNode;
import pacioli.types.ast.SchemaNode;
import pacioli.types.ast.TypeApplicationNode;
import pacioli.types.ast.TypeNode;
import pacioli.types.ast.TypePerNode;

/**
 * Create documentation for the base and standard libraries.
 * 
 * TODO: Compare with libraryDocumentationGenerator on Bundle and see if there
 * is overlap.
 */
public class PrimitivesDocumentation {

    private final String dirName;
    private final List<File> libs;
    private String target;

    public PrimitivesDocumentation(String dirName, List<File> libs, String target) {
        this.dirName = dirName;
        this.libs = libs;
        this.target = target;
    }

    public void generate(String version) throws Exception {

        String extension;

        switch (this.target) {
            case "markdown": {
                extension = ".md";
                break;
            }
            case "structure": {
                extension = ".txt";
                break;
            }
            case "", "html": {
                extension = ".html";
                break;
            }
            default: {
                throw new PacioliException("Unknown target: " + target);
            }
        }

        Pacioli.log("Generating built-in %s documentation in directory %s", this.target, dirName);

        writeAPIFile("base" + extension, version, "base");

        writeAPIFile("io" + extension, version, "io");
        writeAPIFile("string" + extension, version, "string");
        writeAPIFile("list" + extension, version, "list");
        writeAPIFile("array" + extension, version, "array");
        writeAPIFile("map" + extension, version, "map");
        writeAPIFile("matrix" + extension, version, "matrix");
        writeAPIFile("system" + extension, version, "system");
        writeAPIFile("misc" + extension, version, "misc");
    }

    private void writeAPIFile(String name, String version, String module) throws Exception {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(new File(dirName, name), Pacioli.CHARSET))) {
            writer.write(String.format("<!-- Generated by Pacioli %s -->", Pacioli.VERSION));
            generateBaseAPI(writer, version, module);
        }
    }

    static List<String> PARAM_NAMES = List.of("x", "y", "z", "u", "v", "w", "a", "b", "c", "d", "e", "f", "g", "h");
    static List<String> MATRIX_PARAM_NAMES = List.of("A", "B", "C", "D", "E", "F");

    private void generateBaseAPI(Writer writer, String version, String module)
            throws Exception {

        List<ValueInfo> infos = new ArrayList<>();

        DocumentationGenerator generator = new DocumentationGenerator(module, version).addVersionInfo(true);

        File docFile = null;

        // See if the module exists in base.
        File basePath = new File(libs.get(0), "base/" + module + ".pacioli");
        PacioliFile baseFile = PacioliFile.fromPrimitiveSubLibrary(basePath, "irrelevant", module, true);

        if (baseFile.fsFile().exists()) {
            boolean hasDocFile = baseFile.docFile().exists();

            Pacioli.log("Found library '%s' in base (%s docfile), loading definitions...",
                    module,
                    hasDocFile ? "no" : "with");

            PacioliTable program = Program.load(baseFile).desugar().generateInfos();

            for (ValueInfo info : program.values().allInfos()) {
                infos.add(info);
            }

            if (hasDocFile) {
                docFile = baseFile.docFile();
            }
        }

        // See if the module exists in standard.
        File standardPath = new File(libs.get(0), "standard/" + module + ".pacioli");
        PacioliFile standardFile = PacioliFile.fromPrimitiveSubLibrary(standardPath, "irrelevant", module, true);

        if (standardFile.fsFile().exists()) {
            boolean hasDocFile = standardFile.docFile().exists();

            Pacioli.log("Found library '%s' in standard (%s docfile), loading definitions...",
                    module,
                    hasDocFile ? "no" : "with");

            PacioliTable program = Program.load(standardFile).desugar().generateInfos();

            for (ValueInfo info : program.values().allInfos()) {
                infos.add(info);
            }

            if (docFile != null && hasDocFile) {
                Pacioli.log("WARNING: found .doc file for '%s' in base and standard, skipping the doc from base!",
                        module,
                        hasDocFile ? "no" : "with");
            }

            if (hasDocFile) {
                docFile = standardFile.docFile();
            }

        }

        if (docFile != null) {
            if (docFile.exists()) {
                Pacioli.log("Using doc file %s, including contents...", docFile.getAbsolutePath());
                generator.setIntroFromDocFile(docFile);
            } else {
                Pacioli.log("No doc file, using standard intro...");
            }
        }

        for (ValueInfo info : infos) {
            if (info.isPublic() && info.declaredType().isPresent()) {
                addInfo(info, generator);
            }
        }

        generator.generate(writer, target);
    }

    static public void addInfo(ValueInfo info, DocumentationGenerator generator) {

        TypeNode type = info.declaredType().get();
        if (type instanceof SchemaNode && ((SchemaNode) type).type instanceof FunctionTypeNode) {

            List<String> args = null;

            // Get the arguments from the function definition if it exists. This
            // should work for the standard lib
            if (info.definition().isPresent()) {
                ExpressionNode body = info.definition().get().body;
                if (body instanceof LambdaNode) {
                    LambdaNode lambda = (LambdaNode) body;
                    args = lambda.arguments;
                }
            }

            // If no definition exists it must be a function from the base lib. Just
            // invent parameter names.
            if (args == null) {
                FunctionTypeNode fun = (FunctionTypeNode) ((SchemaNode) type).type;
                if (fun.domain instanceof TypeApplicationNode) {
                    TypeApplicationNode tuple = (TypeApplicationNode) fun.domain;
                    List<String> params = new ArrayList<>();
                    int p = 0;
                    int q = 0;
                    for (TypeNode arg : tuple.args) {
                        if (arg instanceof TypePerNode) {
                            params.add(MATRIX_PARAM_NAMES.get(q++));
                        } else {
                            params.add(PARAM_NAMES.get(p++));
                        }
                    }
                    args = params;
                    // args = paramNames.subList(0, tuple.args.size());
                } else {
                    // Must be function 'tuple' or 'format'
                    args = List.of("...");
                }
            }

            if (info.definition().isPresent()) { // foute check. acos etc gaat fout. Hebben wel body, maar zijn
                                                 // primitive!?
                generator.addFunction(info.name(), args, type.pretty());
                if (info.generalInfo().documentation().isPresent()) {
                    generator.addValueDoc(info.name(), info.generalInfo().documentation().get());
                }

            } else {
                generator.addPrimitiveFunction(info.name(), args, type.pretty());
                if (info.generalInfo().documentation().isPresent()) {
                    generator.addValueDoc(info.name(), info.generalInfo().documentation().get());
                }

            }

            if (info.generalInfo().documentation().isEmpty()) {
                Pacioli.log("  no documentation for function %s", info.name());
            }

        } else {

            if (info.definition().isPresent()) {
                generator.addValue(info.name(), type.pretty());
                if (info.generalInfo().documentation().isPresent()) {
                    generator.addValueDoc(info.name(), info.generalInfo().documentation().get());
                }
            } else {
                generator.addPrimitiveValue(info.name(), type.pretty());
                if (info.generalInfo().documentation().isPresent()) {
                    generator.addValueDoc(info.name(), info.generalInfo().documentation().get());
                }
            }

            if (info.generalInfo().documentation().isEmpty()) {
                Pacioli.log("  no documentation for value %s", info.name());
            }
        }
    }
}
