/* Runtime Support for the Pacioli language
 *
 * Copyright (c) 2023 Paul Griffioen
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

import { Coordinates } from "./values/coordinates";
import { MatrixShape } from "./values/matrix-shape";

/**
 * All possible raw Pacioli values. The unboxed values used by the primitive
 * functions.
 */
export type RawValue =
  | RawMatrix
  | RawList
  | RawTuple
  | RawArray
  | RawRef
  | RawCoordinates
  | RawFunction
  | RawBoole
  | RawString;

export type MatrixStorage = 0 | 1 | 2 | 3; // Full, DOK, COO or CCS

export const STORAGE_FULL = 0;
export const STORAGE_DOK = 1;
export const STORAGE_COO = 2;
export const STORAGE_CCS = 3;

/**
 * Type of an unboxed matrix. Implemented as a nested array of numbers with some
 * extra properties (nr rows, nr columns, and storage kind). The meaning of the
 * numbers depends on the storage kind.
 */
export interface RawMatrix extends Array<Array<number>> {
  kind: "matrix";
  nrRows: number;
  nrColumns: number;
  shape?: MatrixShape; // see oneNumbersFromShape
  storage: MatrixStorage;
}

/**
 * Type of an unboxed Pacioli tuple. A javascript array tagged with kind 'tuple'.
 */
export interface RawTuple extends Array<RawValue> {
  kind: "tuple";
}

/**
 * Type of an unboxed Pacioli list. A javascript array tagged with kind 'list'.
 */
export interface RawList extends Array<RawValue> {
  kind: "list";
}

/**
 * Type of an unboxed Pacioli array. A javascript array tagged with kind 'array'.
 */
export interface RawArray extends Array<RawValue> {
  kind: "array";
}

/**
 * Type of an unboxed mutable Pacioli value. A javascript array tagged with kind 'ref'.
 */
export interface RawRef extends Array<RawValue> {
  kind: "ref";
}

/**
 * Type of an unboxed Pacioli coordinates object. Index sets elements are represented by
 * the position in the index set. The size is the size of the index set.
 */
export interface RawCoordinates {
  kind: "coordinates";
  position: number;
  size: number;
  coords?: Coordinates; // TODO: check when it exists. $base_matrix_row_domain does not provide it!
}

/**
 * Type of the raw (unboxed) Pacioli functions generated by the compiler.
 *
 * Conceptually Pacioli's functions are of type:
 *
 *   RawTuple => RawValue.
 *
 * The compiler maps this to a vararg function:
 *
 *   (...RawValue[]) => RawValue.
 *
 */
export type RawFunction = (...args: RawValue[]) => RawValue;

/**
 * Type of an unboxed Pacioli string. Maps directly to a javascript string.
 */
export type RawString = string;

/**
 * Type of an unboxed Pacioli boolean. Maps directly to a javascript boolean.
 */
export type RawBoole = boolean;

/**
 * Pacioli's nothing value.
 */
export const NOTHING = undefined;

export function tagList(value: Array<RawValue>): RawList {
  (value as RawList).kind = "list";
  return value as RawList;
}

export function tagTuple(value: Array<RawValue>): RawTuple {
  (value as RawTuple).kind = "tuple";
  return value as RawTuple;
}

export function tagArray(value: Array<RawValue>): RawArray {
  (value as RawArray).kind = "array";
  return value as RawArray;
}

export function tagRef(value: Array<RawValue>): RawRef {
  (value as RawRef).kind = "ref";
  return value as RawRef;
}
