/* Runtime Support for the Pacioli language
 *
 * Copyright (c) 2023 Paul Griffioen
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

import { PacioliType } from "./type";
import { PacioliBoole } from "./values/boole";
import { Coordinates } from "./values/coordinates";
import { PacioliFunction } from "./values/function";
import { Matrix } from "./values/matrix";
import { MatrixShape } from "./values/matrix-shape";
import { Maybe } from "./values/maybe";
import { PacioliString } from "./values/string";
import { Void } from "./values/void";

/* Runtime Types
 *
 * A value's type is a Type object with a kind and a param according to
 * the following table:
 *
 *   Kind             | Type Param               | Value
 *   -----------------+--------------------------+-----------------------
 *   boole            | -                        | js boole
 *   matrix           | Shape Object             | Full, DOK, COO or CCS array
 *   coordinate       | Coordinate Object        | js Object {position: i, size: n} with 0<=i<n
 *   function         | Function                 | js Function
 *   tuple            | List of Element Type     | js Array
 *   list             | Element Type             | js Array
 *   reference        | Element Type             | Singleton js Array
 *   void             | null                     | null
 *
 * Notes:
 * - A value that is not a Boole or Function is tagged with its kind
 * - An unknown type (for empty lists and refs) is indicated with null.
 * - A matrix is additionally tagged with its storage, nrRows and nrColumns
 * - The coordinate object is a representative. Its names are ignored.
 * - See file numbers.js for the Full, DOK, COO or CCS arrays
 */

/**
 * Typescript type tags for all possible run time Pacioli values. The types form a
 * discriminating union.
 */

// TODO: strip!
export type RawTag =
  // | "numbers"
  | "position"
  | "boole"
  | "function"
  // | "tuple"
  // | "list"
  | "reference"
  | "void"
  | "maybe"
  | "primitive";

// should be somehting like  type RawValue = RawTagged | string | boole | function
// export type RawMatrix = number[][];
export interface RawMatrix extends Array<Array<number>> {
  kind: "matrix";
  nrRows: number;
  nrColumns: number;
  shape?: MatrixShape; // see oneNumbersFromShape
  storage: 0 | 1 | 2 | 3;
}

export type RawValue =
  | RawTagged
  | RawCoordinates
  | RawMatrix
  | RawList
  | RawTuple;
// export type RawTuple = RawValue[];

/**
 * Type of the raw (unboxed) Pacioli functions generated by the compiler.
 *
 * Conceptually Pacioli's functions are of type:
 *
 *   RawTuple => RawValue.
 *
 * The compiler maps this to a vararg function:
 *
 *   (...RawTuple) => RawValue.
 *
 */
export type RawFunction = (...args: RawTuple) => RawValue;

export interface RawTuple extends Array<RawValue> {
  kind: "tuple";
}

export interface RawArray extends Array<RawValue> {
  kind: "array";
}

export interface RawList extends Array<RawValue> {
  kind: "list";
}

export interface RawRef extends Array<RawValue> {}

export type RawString = string;
export type RawBoole = boolean;

export const NOTHING = undefined;
export const VOID = undefined;

export interface RawTagged {
  readonly kind: RawTag;
}

export interface RawCoordinates {
  kind: "coordinates";
  position: number;
  size: number;
  coords?: Coordinates; // TODO: check when it exists. $base_matrix_row_domain does not provide it!
}

/**
 * Not typesafe!
 *
 * @param value
 * @param kind
 * @returns
 */
export function tagKind(
  value: any,
  kind: "tuple" | "list" | "reference" | "void"
): Tagged {
  value.kind = kind;
  return value as Tagged;
}

export function tagList(value: Array<RawValue>): RawList {
  (value as RawList).kind = "list";
  return value as RawList;
}

export function tagTuple(value: Array<RawValue>): RawTuple {
  (value as RawTuple).kind = "tuple";
  return value as RawTuple;
}

export function tagArray(value: Array<RawValue>): RawArray {
  (value as RawArray).kind = "array";
  return value as RawArray;
}

export function makeRawTuple(args: RawValue[]): RawTuple {
  let arr = Array.prototype.slice.call(args) as RawTuple;
  arr.kind = "tuple";
  return arr;
}

export function tagType(value: any, type: PacioliType): Tagged {
  value.type = type;
  return value as Tagged;
}

// TaggedArray noemen
export interface Tagged {
  readonly kind: "tuple" | "list" | "reference";
}

export type PacioliValue =
  | Matrix
  | Coordinates
  | Tagged
  | PacioliBoole
  | PacioliFunction
  | PacioliString
  | Void
  | Maybe<any>;

export interface ToText {
  toText(): string;
}
