// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/pacioli/parser/lexer.flex

package pacioli.parser;

// java -jar jflex-full-1.8.2.jar lexer.flex

import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java.io.File;
import pacioli.compiler.PacioliException;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRINGSEQ = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\12\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\3\10"+
    "\1\33\15\10\1\34\1\10\1\35\6\10\1\36\1\37"+
    "\1\40\1\41\1\42\1\0\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\2\10\1\54\1\55"+
    "\1\56\1\57\1\60\1\10\1\61\1\62\1\63\1\64"+
    "\1\65\1\66\1\67\1\70\1\10\1\71\1\72\1\73"+
    "\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\2\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\1\1\24"+
    "\1\25\1\26\1\27\1\30\14\5\1\31\1\32\1\33"+
    "\1\34\1\35\1\1\1\0\1\36\1\2\5\0\1\37"+
    "\2\0\1\40\1\41\1\42\1\43\1\0\1\44\1\0"+
    "\1\45\1\46\1\47\3\5\1\50\5\5\1\51\1\5"+
    "\1\52\1\5\1\53\6\5\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\3\0\1\62\1\0\1\63\1\64\2\0"+
    "\1\65\1\66\1\67\1\70\1\71\1\72\3\5\1\73"+
    "\1\5\1\74\5\5\1\75\1\76\6\5\1\77\1\100"+
    "\1\101\1\102\1\0\10\5\1\103\6\5\1\104\1\105"+
    "\2\5\1\106\10\5\1\0\11\5\1\107\1\110\5\5"+
    "\1\111\4\5\1\0\1\112\1\5\1\113\2\5\1\114"+
    "\1\5\1\115\1\116\1\117\2\5\1\120\3\5\1\121"+
    "\1\122\1\123\3\5\1\124\1\125\1\126\1\127\3\5"+
    "\1\130\1\131\1\5\1\132\1\133\1\5\1\134";

  private static int [] zzUnpackAction() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\170\0\264\0\360\0\170\0\u012c"+
    "\0\u0168\0\170\0\u01a4\0\170\0\170\0\170\0\170\0\170"+
    "\0\u01e0\0\u021c\0\u0258\0\u0294\0\170\0\u02d0\0\u030c\0\u0348"+
    "\0\u0384\0\170\0\170\0\170\0\170\0\u03c0\0\u03fc\0\u0438"+
    "\0\u0474\0\u04b0\0\u04ec\0\u0528\0\u0564\0\u05a0\0\u05dc\0\u0618"+
    "\0\u0654\0\u0690\0\170\0\170\0\170\0\u06cc\0\170\0\u0708"+
    "\0\u0744\0\170\0\u0780\0\u07bc\0\u07f8\0\u0834\0\u0870\0\u08ac"+
    "\0\170\0\u08e8\0\u0924\0\170\0\170\0\170\0\u0960\0\u099c"+
    "\0\170\0\u09d8\0\170\0\170\0\170\0\u0a14\0\u0a50\0\u0a8c"+
    "\0\u0ac8\0\u0b04\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4\0\u0168\0\u0c30"+
    "\0\u0c6c\0\u0ca8\0\u0168\0\u0ce4\0\u0d20\0\u0d5c\0\u0d98\0\u0dd4"+
    "\0\u0e10\0\170\0\170\0\170\0\170\0\170\0\170\0\u0e4c"+
    "\0\u0e88\0\u0ec4\0\170\0\u0f00\0\170\0\170\0\u0f3c\0\u0f78"+
    "\0\u0924\0\170\0\170\0\170\0\170\0\u0168\0\u0fb4\0\u0ff0"+
    "\0\u102c\0\u0168\0\u1068\0\u0168\0\u10a4\0\u10e0\0\u111c\0\u1158"+
    "\0\u1194\0\u0168\0\u0168\0\u11d0\0\u120c\0\u1248\0\u1284\0\u12c0"+
    "\0\u12fc\0\170\0\170\0\170\0\170\0\u1338\0\u1374\0\u13b0"+
    "\0\u13ec\0\u1428\0\u1464\0\u14a0\0\u14dc\0\u1518\0\u1554\0\u1590"+
    "\0\u15cc\0\u1608\0\u1644\0\u1680\0\u16bc\0\u0168\0\u0168\0\u16f8"+
    "\0\u1734\0\u0168\0\u1770\0\u17ac\0\u17e8\0\u1824\0\u1860\0\u189c"+
    "\0\u18d8\0\u1914\0\u1950\0\u198c\0\u19c8\0\u1a04\0\u1a40\0\u1a7c"+
    "\0\u1ab8\0\u1af4\0\u1b30\0\u1b6c\0\u0168\0\u0168\0\u1ba8\0\u1be4"+
    "\0\u1c20\0\u1c5c\0\u1c98\0\u0168\0\u1cd4\0\u1d10\0\u1d4c\0\u1d88"+
    "\0\u1dc4\0\u0168\0\u1e00\0\u0168\0\u1e3c\0\u1e78\0\u0168\0\u1eb4"+
    "\0\u0168\0\u0168\0\u0168\0\u1ef0\0\u1f2c\0\u0168\0\u1f68\0\u1fa4"+
    "\0\u1fe0\0\u0168\0\u0168\0\170\0\u201c\0\u2058\0\u2094\0\u0168"+
    "\0\u0168\0\u0168\0\u0168\0\u20d0\0\u210c\0\u2148\0\u0168\0\u0168"+
    "\0\u2184\0\u0168\0\u0168\0\u21c0\0\u0168";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\4\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\3\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\3\11\1\33\1\34\1\35\1\36\1\11"+
    "\1\37\1\40\1\11\1\41\1\42\1\43\2\11\1\44"+
    "\1\45\2\11\1\46\1\47\1\50\1\11\1\51\2\11"+
    "\1\52\2\11\1\53\1\54\1\55\6\56\1\57\30\56"+
    "\1\60\34\56\76\0\1\61\120\0\1\62\44\0\2\10"+
    "\1\4\1\63\70\10\10\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\27\11\20\0\1\64\3\0\1\65\1\66"+
    "\14\0\1\67\1\0\1\70\62\0\1\71\60\0\1\72"+
    "\77\0\1\73\1\0\1\23\74\0\1\74\2\0\1\75"+
    "\64\0\1\76\6\0\1\77\73\0\1\100\73\0\1\101"+
    "\75\0\1\102\75\0\1\103\1\104\1\105\46\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\14\11\1\106\12\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\5\11"+
    "\1\107\21\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\5\11\1\110\7\11\1\111\11\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\12\11\1\112\1\11"+
    "\1\113\10\11\1\114\1\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\1\11\1\115\13\11\1\116\11\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\6\11"+
    "\1\117\4\11\1\120\1\121\12\11\13\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\5\11\1\122\21\11\13\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\17\11\1\123"+
    "\7\11\13\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\5\11\1\124\14\11\1\125\4\11\13\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\5\11\1\126\21\11\13\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\10\11\1\127"+
    "\6\11\1\130\7\11\13\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\10\11\1\131\16\11\3\0\6\56\1\0"+
    "\30\56\1\0\34\56\6\0\1\132\30\0\1\133\16\0"+
    "\1\134\2\0\1\135\1\0\1\136\35\0\1\4\50\0"+
    "\1\4\103\0\1\137\6\0\1\140\67\0\1\141\4\0"+
    "\1\142\63\0\1\143\6\0\1\144\64\0\1\145\73\0"+
    "\1\146\61\0\15\147\1\150\56\147\23\0\1\151\77\0"+
    "\1\152\1\153\73\0\1\154\74\0\1\155\52\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\4\11\1\156\22\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\7\11"+
    "\1\157\17\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\3\11\1\160\2\11\1\161\20\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\3\11\1\162\23\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\20\11"+
    "\1\163\6\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\4\11\1\164\22\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\16\11\1\165\10\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\12\11\1\166\14\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\17\11"+
    "\1\167\7\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\16\11\1\170\10\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\3\11\1\171\23\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\21\11\1\172\5\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\17\11"+
    "\1\173\7\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\2\11\1\174\24\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\21\11\1\175\5\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\5\11\1\176\21\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\22\11"+
    "\1\177\4\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\5\11\1\200\3\11\1\201\15\11\15\0\1\202"+
    "\73\0\1\203\73\0\1\204\73\0\1\205\61\0\15\147"+
    "\1\206\56\147\15\0\1\150\4\0\1\4\61\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\11\11\1\207\15\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\12\11"+
    "\1\210\14\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\1\11\1\211\1\11\1\212\5\11\1\213\1\11"+
    "\1\214\5\11\1\215\1\216\4\11\13\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\5\11\1\217\21\11\13\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\15\11\1\220"+
    "\11\11\13\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\20\11\1\177\6\11\13\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\1\221\26\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\15\11\1\222\11\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\12\11\1\223\14\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\12\11"+
    "\1\224\14\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\22\11\1\225\4\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\14\11\1\226\12\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\5\11\1\227\21\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\17\11"+
    "\1\230\7\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\12\11\1\231\14\11\3\0\15\147\1\206\4\147"+
    "\1\4\51\147\10\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\14\11\1\232\12\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\1\11\1\233\25\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\12\11\1\234\14\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\12\11"+
    "\1\235\2\11\1\236\11\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\14\11\1\237\12\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\1\11\1\240\25\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\26\11"+
    "\1\241\13\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\14\11\1\242\12\11\7\0\1\243\3\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\27\11\13\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\17\11\1\244\7\11\13\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\11\11\1\245"+
    "\3\11\1\246\3\11\1\247\1\250\4\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\17\11\1\251\7\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\22\11"+
    "\1\252\4\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\11\11\1\253\15\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\17\11\1\254\7\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\5\11\1\255\21\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\5\11"+
    "\1\256\21\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\17\11\1\257\7\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\11\11\1\260\15\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\1\11\1\261\25\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\14\11"+
    "\1\262\12\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\4\11\1\263\1\264\12\11\1\265\6\11\13\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\21\11\1\266"+
    "\5\11\13\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\16\11\1\267\10\11\13\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\11\11\1\270\15\11\56\0\1\271\30\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\21\11\1\272"+
    "\5\11\13\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\14\11\1\273\12\11\13\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\16\11\1\274\10\11\13\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\26\11\1\275\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\14\11\1\276\12\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\21\11"+
    "\1\277\5\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\4\11\1\300\22\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\3\11\1\301\23\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\14\11\1\302\12\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\5\11"+
    "\1\303\21\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\1\11\1\304\25\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\20\11\1\305\6\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\23\11\1\306\3\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\5\11"+
    "\1\307\21\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\21\11\1\310\5\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\17\11\1\311\7\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\5\11\1\312\21\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\21\11"+
    "\1\313\5\11\53\0\1\314\33\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\4\11\1\315\22\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\16\11\1\316\10\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\11\11"+
    "\1\317\15\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\5\11\1\320\21\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\20\11\1\321\6\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\20\11\1\322\6\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\25\11"+
    "\1\323\1\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\1\11\1\324\25\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\11\11\1\325\15\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\5\11\1\326\21\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\5\11"+
    "\1\327\21\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\21\11\1\330\5\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\14\11\1\331\12\11\13\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\25\11\1\332\1\11"+
    "\13\0\1\11\12\0\1\11\7\0\3\11\4\0\25\11"+
    "\1\333\1\11\13\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\3\11\1\334\23\11\13\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\5\11\1\335\21\11\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8700];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\2\1\1\11\1\1\5\11"+
    "\4\1\1\11\4\1\4\11\15\1\3\11\1\1\1\11"+
    "\1\1\1\0\1\11\1\1\5\0\1\11\2\0\3\11"+
    "\1\1\1\0\1\11\1\0\3\11\24\1\6\11\3\0"+
    "\1\11\1\0\2\11\2\0\1\1\4\11\24\1\4\11"+
    "\1\0\34\1\1\0\25\1\1\0\22\1\1\11\21\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[221];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();
    public Lexer(java.io.Reader in, ComplexSymbolFactory sf, File file, String source){
	this(in);
	symbolFactory = sf;
        this.file = file;
        this.source = source;
    }
    File file;
    String source;
    ComplexSymbolFactory symbolFactory;

  private Symbol symbol(String name, int sym) {
      //return symbolFactory.newSymbol(name, sym, new Location(yyline+1,yycolumn+1,(int)(long)(int)(long)yychar), new Location(yyline+1,yycolumn+yylength(),(int)(long)(int)(long)yychar+yylength()));
      return symbolFactory.newSymbol(name, sym, new Location(yyline, yycolumn, (int)(long)yychar), new Location(yyline, yycolumn+yylength(), (int)(long)yychar+yylength()));
  }

  private Symbol symbol(String name, int sym, Object val) {
      Location left = new Location(yyline, yycolumn, (int)(long)yychar);
      Location right= new Location(yyline, yycolumn+yylength(), (int)(long)yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  
  // Seems wrong. The right line can be on a lower line in a string!
  private Symbol symbol(String name, int sym, Object val,int buflength) {
      Location left = new Location(yyline, yycolumn+yylength()-buflength, (int)(long)yychar+yylength()-buflength);
      Location right= new Location(yyline, yycolumn+yylength(), (int)(long)yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private void error(String message) {
    //pacioli.compiler.Location errorLocation = new pacioli.compiler.Location(file, source, (int)(long)(int)(long)yychar, (int)(long)(int)(long)yychar+yylength());
    pacioli.compiler.Location from = new pacioli.compiler.Location(file, yyline, yycolumn, (int)(long)(int)(long)yychar);
    pacioli.compiler.Location to = new pacioli.compiler.Location(file, yyline, yycolumn+yylength(), (int)(long)(int)(long)yychar+yylength());
    pacioli.compiler.Location errorLocation = from.join(to);
    throw new RuntimeException("Parse error", new PacioliException(errorLocation, message));
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {      return symbolFactory.newSymbol("EOF", EOF, new Location(yyline, yycolumn, (int)(long)(int)(long)yychar), new Location(yyline, yycolumn, (int)(long)(int)(long)yychar));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* throw new Error("Illegal character <"+ yytext()+">");*/
		    error("Illegal character <"+ yytext()+">");
            }
          // fall through
          case 93: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 94: break;
          case 3:
            { return symbol("excl", EXCL);
            }
          // fall through
          case 95: break;
          case 4:
            { string.setLength(0); yybegin(STRINGSEQ);
            }
          // fall through
          case 96: break;
          case 5:
            { return symbol("Identifier",IDENTIFIER, yytext());
            }
          // fall through
          case 97: break;
          case 6:
            { return symbol("mod", MOD);
            }
          // fall through
          case 98: break;
          case 7:
            { return symbol("(",LPAR);
            }
          // fall through
          case 99: break;
          case 8:
            { return symbol(")",RPAR);
            }
          // fall through
          case 100: break;
          case 9:
            { return symbol("mult", MULT);
            }
          // fall through
          case 101: break;
          case 10:
            { return symbol("plus", PLUS);
            }
          // fall through
          case 102: break;
          case 11:
            { return symbol("comma",COMMA);
            }
          // fall through
          case 103: break;
          case 12:
            { return symbol("neg", NEG, NEG);
            }
          // fall through
          case 104: break;
          case 13:
            { return symbol("div", DIV);
            }
          // fall through
          case 105: break;
          case 14:
            { return symbol("Natural", NATURAL, yytext());
            }
          // fall through
          case 106: break;
          case 15:
            { return symbol("colon",COLON);
            }
          // fall through
          case 107: break;
          case 16:
            { return symbol("semicolon",SEMICOLON);
            }
          // fall through
          case 108: break;
          case 17:
            { return symbol("le", LE);
            }
          // fall through
          case 109: break;
          case 18:
            { return symbol("eql", EQL, EQL);
            }
          // fall through
          case 110: break;
          case 19:
            { return symbol("gt", GT);
            }
          // fall through
          case 111: break;
          case 20:
            { return symbol("@", AT);
            }
          // fall through
          case 112: break;
          case 21:
            { return symbol("{",LBRACK);
            }
          // fall through
          case 113: break;
          case 22:
            { return symbol("leftdiv", LEFTDIV);
            }
          // fall through
          case 114: break;
          case 23:
            { return symbol("}",RBRACK);
            }
          // fall through
          case 115: break;
          case 24:
            { return symbol("hat", HAT, HAT);
            }
          // fall through
          case 116: break;
          case 25:
            { return symbol("{",LBRC);
            }
          // fall through
          case 117: break;
          case 26:
            { return symbol("|",PIPE);
            }
          // fall through
          case 118: break;
          case 27:
            { return symbol("}",RBRC);
            }
          // fall through
          case 119: break;
          case 28:
            { string.append(yytext());
            }
          // fall through
          case 120: break;
          case 29:
            { yybegin(YYINITIAL); 
                    return symbol("String", STRING, string.toString(), string.length());
            }
          // fall through
          case 121: break;
          case 30:
            { return symbol("neq", NEQ);
            }
          // fall through
          case 122: break;
          case 31:
            { return symbol("to", TO, TO);
            }
          // fall through
          case 123: break;
          case 32:
            { return symbol("dblcln",DBLCLN);
            }
          // fall through
          case 124: break;
          case 33:
            { return symbol(":=",ASSIGN);
            }
          // fall through
          case 125: break;
          case 34:
            { return symbol("<-",FROM);
            }
          // fall through
          case 126: break;
          case 35:
            { return symbol("leq", LEQ);
            }
          // fall through
          case 127: break;
          case 36:
            { return symbol("gtq", GTQ);
            }
          // fall through
          case 128: break;
          case 37:
            { return symbol("diminv", DIMINV);
            }
          // fall through
          case 129: break;
          case 38:
            { return symbol("reci", RECI);
            }
          // fall through
          case 130: break;
          case 39:
            { return symbol("trans", TRANS);
            }
          // fall through
          case 131: break;
          case 40:
            { return symbol("do",DO);
            }
          // fall through
          case 132: break;
          case 41:
            { return symbol("if",IF);
            }
          // fall through
          case 133: break;
          case 42:
            { return symbol("in",IN);
            }
          // fall through
          case 134: break;
          case 43:
            { return symbol("or", OR);
            }
          // fall through
          case 135: break;
          case 44:
            { string.append('\"');
            }
          // fall through
          case 136: break;
          case 45:
            { string.append('\\');
            }
          // fall through
          case 137: break;
          case 46:
            { string.append('\n');
            }
          // fall through
          case 138: break;
          case 47:
            { string.append('\r');
            }
          // fall through
          case 139: break;
          case 48:
            { string.append('\t');
            }
          // fall through
          case 140: break;
          case 49:
            { return symbol("mmult", MMULT);
            }
          // fall through
          case 141: break;
          case 50:
            { return symbol("mdiv", MDIV);
            }
          // fall through
          case 142: break;
          case 51:
            { return symbol("mleftdiv", MLEFTDIV);
            }
          // fall through
          case 143: break;
          case 52:
            { return symbol("mexpt", MEXPT);
            }
          // fall through
          case 144: break;
          case 53:
            { return symbol("Decimal", DECIMAL, yytext());
            }
          // fall through
          case 145: break;
          case 54:
            { return symbol("followsfrom", FOLLOWSFROM);
            }
          // fall through
          case 146: break;
          case 55:
            { return symbol("equiv", EQUIV);
            }
          // fall through
          case 147: break;
          case 56:
            { return symbol("implies", IMPLIES);
            }
          // fall through
          case 148: break;
          case 57:
            { return symbol("questionmarks", QUESTIONMARKS);
            }
          // fall through
          case 149: break;
          case 58:
            { return symbol("and", AND);
            }
          // fall through
          case 150: break;
          case 59:
            { return symbol("doc",DOC);
            }
          // fall through
          case 151: break;
          case 60:
            { return symbol("end",END);
            }
          // fall through
          case 152: break;
          case 61:
            { return symbol("let",LET);
            }
          // fall through
          case 153: break;
          case 62:
            { return symbol("per",PER);
            }
          // fall through
          case 154: break;
          case 63:
            { return symbol("rscale", RSCALE);
            }
          // fall through
          case 155: break;
          case 64:
            { return symbol("lscale", LSCALE);
            }
          // fall through
          case 156: break;
          case 65:
            { return symbol("lscaledown", LSCALEDOWN);
            }
          // fall through
          case 157: break;
          case 66:
            { return symbol("rscaledown",RSCALEDOWN);
            }
          // fall through
          case 158: break;
          case 67:
            { return symbol("else",ELSE);
            }
          // fall through
          case 159: break;
          case 68:
            { return symbol("then",THEN);
            }
          // fall through
          case 160: break;
          case 69:
            { return symbol("Boolean", BOOLEAN, yytext());
            }
          // fall through
          case 161: break;
          case 70:
            { return symbol("begin",BEGIN);
            }
          // fall through
          case 162: break;
          case 71:
            { return symbol("where",WHERE);
            }
          // fall through
          case 163: break;
          case 72:
            { return symbol("while",WHILE);
            }
          // fall through
          case 164: break;
          case 73:
            { return symbol("define",DEFINE);
            }
          // fall through
          case 165: break;
          case 74:
            { return symbol("export", EXPORT);
            }
          // fall through
          case 166: break;
          case 75:
            { return symbol("for_op",FOROP);
            }
          // fall through
          case 167: break;
          case 76:
            { return symbol("import",IMPORT);
            }
          // fall through
          case 168: break;
          case 77:
            { return symbol("public", PUBLIC);
            }
          // fall through
          case 169: break;
          case 78:
            { return symbol("return",RETURN);
            }
          // fall through
          case 170: break;
          case 79:
            { return symbol("declare",DECLARE);
            }
          // fall through
          case 171: break;
          case 80:
            { return symbol("defconv",DEFCONV);
            }
          // fall through
          case 172: break;
          case 81:
            { return symbol("deftype",DEFTYPE);
            }
          // fall through
          case 173: break;
          case 82:
            { return symbol("defunit",DEFUNIT);
            }
          // fall through
          case 174: break;
          case 83:
            { return symbol("else if",ELSEIF);
            }
          // fall through
          case 175: break;
          case 84:
            { return symbol("include",INCLUDE);
            }
          // fall through
          case 176: break;
          case 85:
            { return symbol("defalias",DEFALIAS);
            }
          // fall through
          case 177: break;
          case 86:
            { return symbol("defclass",DEFCLASS);
            }
          // fall through
          case 178: break;
          case 87:
            { return symbol("defindex",DEFINDEX);
            }
          // fall through
          case 179: break;
          case 88:
            { return symbol("for_type",FORTYPE);
            }
          // fall through
          case 180: break;
          case 89:
            { return symbol("for_unit",FORUNIT);
            }
          // fall through
          case 181: break;
          case 90:
            { return symbol("defmatrix",DEFMATRIX);
            }
          // fall through
          case 182: break;
          case 91:
            { return symbol("for_index",FORINDEX);
            }
          // fall through
          case 183: break;
          case 92:
            { return symbol("definstance",DEFINSTANCE);
            }
          // fall through
          case 184: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
