// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/main/java/pacioli/parser/lexer.flex

package pacioli.parser;

// java -jar jflex-full-1.8.2.jar lexer.flex

import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java.io.File;
import pacioli.compiler.PacioliException;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner, sym {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRINGSEQ = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\0\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\12\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\3\10"+
    "\1\33\15\10\1\34\1\10\1\35\6\10\1\36\1\37"+
    "\1\40\1\41\1\42\1\0\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\2\10\1\54\1\55"+
    "\1\56\1\57\1\60\1\10\1\61\1\62\1\63\1\64"+
    "\1\65\1\66\1\67\1\70\1\10\1\71\1\72\1\73"+
    "\1\74\u0181\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\2\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\1\1\24"+
    "\1\25\1\26\1\27\1\30\16\5\1\31\1\32\1\33"+
    "\1\1\1\34\1\35\1\1\1\0\1\36\1\2\5\0"+
    "\1\37\2\0\1\40\1\41\1\42\1\43\1\0\1\44"+
    "\1\0\1\45\1\46\1\47\2\5\1\50\2\5\1\51"+
    "\6\5\1\52\1\5\1\53\1\5\1\54\7\5\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\3\0\1\64"+
    "\1\0\1\65\1\66\2\0\1\67\1\70\1\71\1\72"+
    "\1\73\1\5\1\74\3\5\1\75\1\5\1\76\2\5"+
    "\1\77\3\5\1\100\1\101\7\5\1\102\1\103\1\104"+
    "\1\105\1\0\13\5\1\106\2\5\1\107\5\5\1\110"+
    "\1\111\3\5\1\112\12\5\1\0\12\5\1\113\1\114"+
    "\7\5\1\115\5\5\1\0\1\116\1\5\1\117\2\5"+
    "\1\120\1\5\1\121\1\122\1\123\1\124\1\125\2\5"+
    "\1\126\1\127\4\5\1\130\1\131\1\132\3\5\1\133"+
    "\1\5\1\134\1\135\1\136\4\5\1\137\1\140\2\5"+
    "\1\141\1\142\1\143\3\5\1\144\5\5\1\145";

  private static int [] zzUnpackAction() {
    int [] result = new int[260];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\172\0\267\0\364\0\172\0\u0131"+
    "\0\u016e\0\172\0\u01ab\0\172\0\172\0\172\0\172\0\172"+
    "\0\u01e8\0\u0225\0\u0262\0\u029f\0\172\0\u02dc\0\u0319\0\u0356"+
    "\0\u0393\0\172\0\172\0\172\0\172\0\u03d0\0\u040d\0\u044a"+
    "\0\u0487\0\u04c4\0\u0501\0\u053e\0\u057b\0\u05b8\0\u05f5\0\u0632"+
    "\0\u066f\0\u06ac\0\u06e9\0\u0726\0\172\0\172\0\172\0\u0763"+
    "\0\u07a0\0\172\0\u07dd\0\u081a\0\172\0\u0857\0\u0894\0\u08d1"+
    "\0\u090e\0\u094b\0\u0988\0\172\0\u09c5\0\u0a02\0\172\0\172"+
    "\0\172\0\u0a3f\0\u0a7c\0\172\0\u0ab9\0\172\0\172\0\172"+
    "\0\u0af6\0\u0b33\0\u016e\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64"+
    "\0\u0ca1\0\u0cde\0\u0d1b\0\u0d58\0\u016e\0\u0d95\0\u0dd2\0\u0e0f"+
    "\0\u016e\0\u0e4c\0\u0e89\0\u0ec6\0\u0f03\0\u0f40\0\u0f7d\0\u0fba"+
    "\0\172\0\172\0\172\0\172\0\172\0\172\0\172\0\u0ff7"+
    "\0\u1034\0\u1071\0\172\0\u10ae\0\172\0\172\0\u10eb\0\u1128"+
    "\0\u0a02\0\172\0\172\0\172\0\172\0\u1165\0\u016e\0\u11a2"+
    "\0\u11df\0\u121c\0\u016e\0\u1259\0\u016e\0\u1296\0\u12d3\0\u1310"+
    "\0\u134d\0\u138a\0\u13c7\0\u016e\0\u016e\0\u1404\0\u1441\0\u147e"+
    "\0\u14bb\0\u14f8\0\u1535\0\u1572\0\172\0\172\0\172\0\172"+
    "\0\u15af\0\u15ec\0\u1629\0\u1666\0\u16a3\0\u16e0\0\u171d\0\u175a"+
    "\0\u1797\0\u17d4\0\u1811\0\u184e\0\u188b\0\u18c8\0\u1905\0\u016e"+
    "\0\u1942\0\u197f\0\u19bc\0\u19f9\0\u1a36\0\u016e\0\u016e\0\u1a73"+
    "\0\u1ab0\0\u1aed\0\u016e\0\u1b2a\0\u1b67\0\u1ba4\0\u1be1\0\u1c1e"+
    "\0\u1c5b\0\u1c98\0\u1cd5\0\u1d12\0\u1d4f\0\u1d8c\0\u1dc9\0\u1e06"+
    "\0\u1e43\0\u1e80\0\u1ebd\0\u1efa\0\u1f37\0\u1f74\0\u1fb1\0\u1fee"+
    "\0\u016e\0\u016e\0\u202b\0\u2068\0\u20a5\0\u20e2\0\u211f\0\u215c"+
    "\0\u2199\0\u016e\0\u21d6\0\u2213\0\u2250\0\u228d\0\u22ca\0\u2307"+
    "\0\u016e\0\u2344\0\u016e\0\u2381\0\u23be\0\u016e\0\u23fb\0\u016e"+
    "\0\u016e\0\u016e\0\u016e\0\u2438\0\u2475\0\u24b2\0\u016e\0\u016e"+
    "\0\u24ef\0\u252c\0\u2569\0\u25a6\0\u016e\0\u016e\0\172\0\u25e3"+
    "\0\u2620\0\u265d\0\u016e\0\u269a\0\u016e\0\u016e\0\u016e\0\u26d7"+
    "\0\u2714\0\u2751\0\u278e\0\u016e\0\u016e\0\u27cb\0\u2808\0\u016e"+
    "\0\u016e\0\u016e\0\u2845\0\u2882\0\u28bf\0\u016e\0\u28fc\0\u2939"+
    "\0\u2976\0\u29b3\0\u29f0\0\u016e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[260];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\4\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\3\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\3\11\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\11\1\42\1\43\1\44\2\11\1\45"+
    "\1\46\2\11\1\47\1\50\1\51\1\52\1\53\2\11"+
    "\1\54\2\11\1\55\1\56\1\57\1\60\6\61\1\62"+
    "\30\61\1\63\35\61\77\0\1\64\121\0\1\65\45\0"+
    "\2\10\1\4\1\66\71\10\10\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\27\11\21\0\1\67\3\0\1\70"+
    "\1\71\14\0\1\72\1\0\1\73\63\0\1\74\61\0"+
    "\1\75\100\0\1\76\1\0\1\23\75\0\1\77\2\0"+
    "\1\100\65\0\1\101\6\0\1\102\74\0\1\103\74\0"+
    "\1\104\76\0\1\105\76\0\1\106\1\107\1\110\47\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\12\11\1\111"+
    "\14\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\14\11\1\112\3\11\1\113\6\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\5\11\1\114\21\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\5\11\1\115"+
    "\7\11\1\116\11\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\12\11\1\117\1\11\1\120\10\11\1\121"+
    "\1\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\1\11\1\122\13\11\1\123\1\11\1\124\7\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\6\11\1\125"+
    "\4\11\1\126\1\127\12\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\5\11\1\130\21\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\17\11\1\131\7\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\5\11"+
    "\1\132\14\11\1\133\4\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\5\11\1\134\21\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\5\11\1\135\21\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\10\11"+
    "\1\136\6\11\1\137\7\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\10\11\1\140\16\11\33\0\1\141"+
    "\45\0\6\61\1\0\30\61\1\0\35\61\6\0\1\142"+
    "\30\0\1\143\16\0\1\144\2\0\1\145\1\0\1\146"+
    "\36\0\1\4\51\0\1\4\104\0\1\147\6\0\1\150"+
    "\70\0\1\151\4\0\1\152\64\0\1\153\6\0\1\154"+
    "\65\0\1\155\74\0\1\156\62\0\15\157\1\160\57\157"+
    "\23\0\1\161\100\0\1\162\1\163\74\0\1\164\75\0"+
    "\1\165\53\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\1\11\1\166\25\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\4\11\1\167\22\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\7\11\1\170\17\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\3\11\1\171"+
    "\2\11\1\172\20\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\3\11\1\173\23\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\20\11\1\174\6\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\4\11\1\175"+
    "\22\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\16\11\1\176\10\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\12\11\1\177\14\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\17\11\1\200\7\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\15\11\1\201"+
    "\11\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\16\11\1\202\10\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\3\11\1\203\23\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\21\11\1\204\5\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\17\11\1\205"+
    "\7\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\2\11\1\206\24\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\21\11\1\207\5\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\12\11\1\210\14\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\5\11\1\211"+
    "\21\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\22\11\1\212\4\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\5\11\1\213\3\11\1\214\15\11\16\0"+
    "\1\215\74\0\1\216\74\0\1\217\74\0\1\220\62\0"+
    "\15\157\1\221\57\157\15\0\1\160\4\0\1\4\62\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\13\11\1\222"+
    "\13\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\11\11\1\223\15\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\12\11\1\224\14\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\1\11\1\225\1\11\1\226"+
    "\1\227\4\11\1\230\1\11\1\231\3\11\1\232\1\11"+
    "\1\233\1\234\4\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\5\11\1\235\21\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\15\11\1\236\11\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\20\11\1\212"+
    "\6\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\1\237\26\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\13\11\1\240\13\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\15\11\1\241\11\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\12\11\1\242\14\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\12\11"+
    "\1\243\14\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\22\11\1\244\4\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\5\11\1\245\21\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\14\11\1\246\12\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\5\11"+
    "\1\247\21\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\17\11\1\250\7\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\12\11\1\251\14\11\4\0\15\157"+
    "\1\221\4\157\1\4\52\157\10\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\2\11\1\252\24\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\14\11\1\253\12\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\1\11"+
    "\1\254\25\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\12\11\1\255\14\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\12\11\1\256\2\11\1\257\11\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\1\11"+
    "\1\260\25\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\14\11\1\261\12\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\1\11\1\262\25\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\5\11\1\263\21\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\26\11"+
    "\1\264\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\14\11\1\265\12\11\10\0\1\266\3\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\27\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\17\11\1\267\7\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\11\11\1\270"+
    "\3\11\1\271\3\11\1\272\1\273\4\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\17\11\1\274\7\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\22\11"+
    "\1\275\4\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\11\11\1\276\15\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\17\11\1\277\7\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\3\11\1\300\23\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\5\11"+
    "\1\301\21\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\5\11\1\302\21\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\4\11\1\303\22\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\17\11\1\304\7\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\11\11"+
    "\1\305\15\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\1\11\1\306\25\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\14\11\1\307\12\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\21\11\1\310\5\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\4\11"+
    "\1\311\1\312\12\11\1\313\6\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\21\11\1\314\5\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\3\11\1\315"+
    "\23\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\16\11\1\316\10\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\11\11\1\317\15\11\57\0\1\320\31\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\21\11\1\321"+
    "\5\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\14\11\1\322\12\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\16\11\1\323\10\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\26\11\1\324\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\14\11\1\325\12\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\21\11"+
    "\1\326\5\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\4\11\1\327\22\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\3\11\1\330\23\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\14\11\1\331\12\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\21\11"+
    "\1\332\5\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\1\11\1\333\25\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\5\11\1\334\21\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\1\11\1\335\25\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\20\11"+
    "\1\336\6\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\23\11\1\337\3\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\1\11\1\340\25\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\5\11\1\341\21\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\21\11"+
    "\1\342\5\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\17\11\1\343\7\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\15\11\1\344\11\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\5\11\1\345\21\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\21\11"+
    "\1\346\5\11\54\0\1\347\34\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\4\11\1\350\22\11\14\0\1\11"+
    "\12\0\1\11\7\0\3\11\4\0\16\11\1\351\10\11"+
    "\14\0\1\11\12\0\1\11\7\0\3\11\4\0\11\11"+
    "\1\352\15\11\14\0\1\11\12\0\1\11\7\0\3\11"+
    "\4\0\5\11\1\353\21\11\14\0\1\11\12\0\1\11"+
    "\7\0\3\11\4\0\1\354\26\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\20\11\1\355\6\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\20\11\1\356"+
    "\6\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\25\11\1\357\1\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\1\11\1\360\25\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\11\11\1\361\15\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\17\11\1\362"+
    "\7\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\5\11\1\363\21\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\5\11\1\364\21\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\21\11\1\365\5\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\16\11\1\366"+
    "\10\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\14\11\1\367\12\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\25\11\1\370\1\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\4\11\1\371\22\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\25\11\1\372"+
    "\1\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\17\11\1\373\7\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\3\11\1\374\23\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\11\11\1\375\15\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\5\11\1\376"+
    "\21\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\13\11\1\377\13\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\11\11\1\u0100\15\11\14\0\1\11\12\0"+
    "\1\11\7\0\3\11\4\0\21\11\1\u0101\5\11\14\0"+
    "\1\11\12\0\1\11\7\0\3\11\4\0\11\11\1\u0102"+
    "\15\11\14\0\1\11\12\0\1\11\7\0\3\11\4\0"+
    "\23\11\1\u0103\3\11\14\0\1\11\12\0\1\11\7\0"+
    "\3\11\4\0\5\11\1\u0104\21\11\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10797];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\2\1\1\11\1\1\5\11"+
    "\4\1\1\11\4\1\4\11\17\1\3\11\2\1\1\11"+
    "\1\1\1\0\1\11\1\1\5\0\1\11\2\0\3\11"+
    "\1\1\1\0\1\11\1\0\3\11\30\1\7\11\3\0"+
    "\1\11\1\0\2\11\2\0\1\1\4\11\27\1\4\11"+
    "\1\0\44\1\1\0\31\1\1\0\26\1\1\11\35\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[260];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();
    public Lexer(java.io.Reader in, ComplexSymbolFactory sf, File file, String source){
	this(in);
	symbolFactory = sf;
        this.file = file;
        this.source = source;
    }
    File file;
    String source;
    ComplexSymbolFactory symbolFactory;

  private Symbol symbol(String name, int sym) {
      //return symbolFactory.newSymbol(name, sym, new Location(yyline+1,yycolumn+1,(int)(long)(int)(long)yychar), new Location(yyline+1,yycolumn+yylength(),(int)(long)(int)(long)yychar+yylength()));
      return symbolFactory.newSymbol(name, sym, new Location(yyline, yycolumn, (int)(long)yychar), new Location(yyline, yycolumn+yylength(), (int)(long)yychar+yylength()));
  }

  private Symbol symbol(String name, int sym, Object val) {
      Location left = new Location(yyline, yycolumn, (int)(long)yychar);
      Location right= new Location(yyline, yycolumn+yylength(), (int)(long)yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  
  // Seems wrong. The right line can be on a lower line in a string!
  private Symbol symbol(String name, int sym, Object val,int buflength) {
      Location left = new Location(yyline, yycolumn+yylength()-buflength, (int)(long)yychar+yylength()-buflength);
      Location right= new Location(yyline, yycolumn+yylength(), (int)(long)yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private void error(String message) {
    //pacioli.compiler.Location errorLocation = new pacioli.compiler.Location(file, source, (int)(long)(int)(long)yychar, (int)(long)(int)(long)yychar+yylength());
    pacioli.compiler.Location from = new pacioli.compiler.Location(file, yyline, yycolumn, (int)(long)(int)(long)yychar);
    pacioli.compiler.Location to = new pacioli.compiler.Location(file, yyline, yycolumn+yylength(), (int)(long)(int)(long)yychar+yylength());
    pacioli.compiler.Location errorLocation = from.join(to);
    throw new RuntimeException("Parse error", new PacioliException(errorLocation, message));
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {      return symbolFactory.newSymbol("EOF", EOF, new Location(yyline, yycolumn, (int)(long)(int)(long)yychar), new Location(yyline, yycolumn, (int)(long)(int)(long)yychar));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* throw new Error("Illegal character <"+ yytext()+">");*/
		    error("Illegal character <"+ yytext()+">");
            }
          // fall through
          case 102: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 103: break;
          case 3:
            { return symbol("excl", EXCL);
            }
          // fall through
          case 104: break;
          case 4:
            { string.setLength(0); yybegin(STRINGSEQ);
            }
          // fall through
          case 105: break;
          case 5:
            { return symbol("Identifier",IDENTIFIER, yytext());
            }
          // fall through
          case 106: break;
          case 6:
            { return symbol("mod", MOD);
            }
          // fall through
          case 107: break;
          case 7:
            { return symbol("(",LPAR);
            }
          // fall through
          case 108: break;
          case 8:
            { return symbol(")",RPAR);
            }
          // fall through
          case 109: break;
          case 9:
            { return symbol("mult", MULT);
            }
          // fall through
          case 110: break;
          case 10:
            { return symbol("plus", PLUS);
            }
          // fall through
          case 111: break;
          case 11:
            { return symbol("comma",COMMA);
            }
          // fall through
          case 112: break;
          case 12:
            { return symbol("neg", NEG, NEG);
            }
          // fall through
          case 113: break;
          case 13:
            { return symbol("div", DIV);
            }
          // fall through
          case 114: break;
          case 14:
            { return symbol("Natural", NATURAL, yytext());
            }
          // fall through
          case 115: break;
          case 15:
            { return symbol("colon",COLON);
            }
          // fall through
          case 116: break;
          case 16:
            { return symbol("semicolon",SEMICOLON);
            }
          // fall through
          case 117: break;
          case 17:
            { return symbol("le", LE);
            }
          // fall through
          case 118: break;
          case 18:
            { return symbol("eql", EQL, EQL);
            }
          // fall through
          case 119: break;
          case 19:
            { return symbol("gt", GT);
            }
          // fall through
          case 120: break;
          case 20:
            { return symbol("@", AT);
            }
          // fall through
          case 121: break;
          case 21:
            { return symbol("{",LBRACK);
            }
          // fall through
          case 122: break;
          case 22:
            { return symbol("leftdiv", LEFTDIV);
            }
          // fall through
          case 123: break;
          case 23:
            { return symbol("}",RBRACK);
            }
          // fall through
          case 124: break;
          case 24:
            { return symbol("hat", HAT, HAT);
            }
          // fall through
          case 125: break;
          case 25:
            { return symbol("{",LBRC);
            }
          // fall through
          case 126: break;
          case 26:
            { return symbol("|",PIPE);
            }
          // fall through
          case 127: break;
          case 27:
            { return symbol("}",RBRC);
            }
          // fall through
          case 128: break;
          case 28:
            { string.append(yytext());
            }
          // fall through
          case 129: break;
          case 29:
            { yybegin(YYINITIAL); 
                    return symbol("String", STRING, string.toString(), string.length());
            }
          // fall through
          case 130: break;
          case 30:
            { return symbol("neq", NEQ);
            }
          // fall through
          case 131: break;
          case 31:
            { return symbol("to", TO, TO);
            }
          // fall through
          case 132: break;
          case 32:
            { return symbol("dblcln",DBLCLN);
            }
          // fall through
          case 133: break;
          case 33:
            { return symbol(":=",ASSIGN);
            }
          // fall through
          case 134: break;
          case 34:
            { return symbol("<-",FROM);
            }
          // fall through
          case 135: break;
          case 35:
            { return symbol("leq", LEQ);
            }
          // fall through
          case 136: break;
          case 36:
            { return symbol("gtq", GTQ);
            }
          // fall through
          case 137: break;
          case 37:
            { return symbol("diminv", DIMINV);
            }
          // fall through
          case 138: break;
          case 38:
            { return symbol("reci", RECI);
            }
          // fall through
          case 139: break;
          case 39:
            { return symbol("trans", TRANS);
            }
          // fall through
          case 140: break;
          case 40:
            { return symbol("as",AS);
            }
          // fall through
          case 141: break;
          case 41:
            { return symbol("do",DO);
            }
          // fall through
          case 142: break;
          case 42:
            { return symbol("if",IF);
            }
          // fall through
          case 143: break;
          case 43:
            { return symbol("in",IN);
            }
          // fall through
          case 144: break;
          case 44:
            { return symbol("or", OR);
            }
          // fall through
          case 145: break;
          case 45:
            { return symbol("appr_eql", APPR_EQL, APPR_EQL);
            }
          // fall through
          case 146: break;
          case 46:
            { string.append('\"');
            }
          // fall through
          case 147: break;
          case 47:
            { string.append('\\');
            }
          // fall through
          case 148: break;
          case 48:
            { string.append('\n');
            }
          // fall through
          case 149: break;
          case 49:
            { string.append('\r');
            }
          // fall through
          case 150: break;
          case 50:
            { string.append('\t');
            }
          // fall through
          case 151: break;
          case 51:
            { return symbol("mmult", MMULT);
            }
          // fall through
          case 152: break;
          case 52:
            { return symbol("mdiv", MDIV);
            }
          // fall through
          case 153: break;
          case 53:
            { return symbol("mleftdiv", MLEFTDIV);
            }
          // fall through
          case 154: break;
          case 54:
            { return symbol("mexpt", MEXPT);
            }
          // fall through
          case 155: break;
          case 55:
            { return symbol("Decimal", DECIMAL, yytext());
            }
          // fall through
          case 156: break;
          case 56:
            { return symbol("followsfrom", FOLLOWSFROM);
            }
          // fall through
          case 157: break;
          case 57:
            { return symbol("equiv", EQUIV);
            }
          // fall through
          case 158: break;
          case 58:
            { return symbol("implies", IMPLIES);
            }
          // fall through
          case 159: break;
          case 59:
            { return symbol("questionmarks", QUESTIONMARKS);
            }
          // fall through
          case 160: break;
          case 60:
            { return symbol("and", AND);
            }
          // fall through
          case 161: break;
          case 61:
            { return symbol("doc",DOC);
            }
          // fall through
          case 162: break;
          case 62:
            { return symbol("end",END);
            }
          // fall through
          case 163: break;
          case 63:
            { return symbol("for",FOR);
            }
          // fall through
          case 164: break;
          case 64:
            { return symbol("let",LET);
            }
          // fall through
          case 165: break;
          case 65:
            { return symbol("per",PER);
            }
          // fall through
          case 166: break;
          case 66:
            { return symbol("rscale", RSCALE);
            }
          // fall through
          case 167: break;
          case 67:
            { return symbol("lscale", LSCALE);
            }
          // fall through
          case 168: break;
          case 68:
            { return symbol("lscaledown", LSCALEDOWN);
            }
          // fall through
          case 169: break;
          case 69:
            { return symbol("rscaledown",RSCALEDOWN);
            }
          // fall through
          case 170: break;
          case 70:
            { return symbol("else",ELSE);
            }
          // fall through
          case 171: break;
          case 71:
            { return symbol("from",QFROM);
            }
          // fall through
          case 172: break;
          case 72:
            { return symbol("then",THEN);
            }
          // fall through
          case 173: break;
          case 73:
            { return symbol("Boolean", BOOLEAN, yytext());
            }
          // fall through
          case 174: break;
          case 74:
            { return symbol("begin",BEGIN);
            }
          // fall through
          case 175: break;
          case 75:
            { return symbol("where",WHERE);
            }
          // fall through
          case 176: break;
          case 76:
            { return symbol("while",WHILE);
            }
          // fall through
          case 177: break;
          case 77:
            { return symbol("define",DEFINE);
            }
          // fall through
          case 178: break;
          case 78:
            { return symbol("export", EXPORT);
            }
          // fall through
          case 179: break;
          case 79:
            { return symbol("for_op",FOROP);
            }
          // fall through
          case 180: break;
          case 80:
            { return symbol("import",IMPORT);
            }
          // fall through
          case 181: break;
          case 81:
            { return symbol("public", PUBLIC);
            }
          // fall through
          case 182: break;
          case 82:
            { return symbol("return",RETURN);
            }
          // fall through
          case 183: break;
          case 83:
            { return symbol("select",SELECT);
            }
          // fall through
          case 184: break;
          case 84:
            { return symbol("lambda", LAMBDA);
            }
          // fall through
          case 185: break;
          case 85:
            { return symbol("declare",DECLARE);
            }
          // fall through
          case 186: break;
          case 86:
            { return symbol("defconv",DEFCONV);
            }
          // fall through
          case 187: break;
          case 87:
            { return symbol("defdata",DEFDATA);
            }
          // fall through
          case 188: break;
          case 88:
            { return symbol("deftype",DEFTYPE);
            }
          // fall through
          case 189: break;
          case 89:
            { return symbol("defunit",DEFUNIT);
            }
          // fall through
          case 190: break;
          case 90:
            { return symbol("else if",ELSEIF);
            }
          // fall through
          case 191: break;
          case 91:
            { return symbol("include",INCLUDE);
            }
          // fall through
          case 192: break;
          case 92:
            { return symbol("defalias",DEFALIAS);
            }
          // fall through
          case 193: break;
          case 93:
            { return symbol("defclass",DEFCLASS);
            }
          // fall through
          case 194: break;
          case 94:
            { return symbol("defindex",DEFINDEX);
            }
          // fall through
          case 195: break;
          case 95:
            { return symbol("for_type",FORTYPE);
            }
          // fall through
          case 196: break;
          case 96:
            { return symbol("for_unit",FORUNIT);
            }
          // fall through
          case 197: break;
          case 97:
            { return symbol("defmatrix",DEFMATRIX);
            }
          // fall through
          case 198: break;
          case 98:
            { return symbol("defrecord",DEFRECORD);
            }
          // fall through
          case 199: break;
          case 99:
            { return symbol("for_index",FORINDEX);
            }
          // fall through
          case 200: break;
          case 100:
            { return symbol("definstance",DEFINSTANCE);
            }
          // fall through
          case 201: break;
          case 101:
            { return symbol("declare_primitive",DECLARE_PRIMITIVE);
            }
          // fall through
          case 202: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
