
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pacioli.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AT = 32;
  public static final int IDENTIFIER = 76;
  public static final int FROM = 23;
  public static final int GT = 66;
  public static final int MMULT = 48;
  public static final int NATURAL = 74;
  public static final int MEXPT = 53;
  public static final int RSCALE = 56;
  public static final int EQUIV = 64;
  public static final int RBRACK = 42;
  public static final int TRANS = 59;
  public static final int COMMA = 36;
  public static final int LSCALE = 58;
  public static final int DEFINE = 4;
  public static final int LBRACK = 41;
  public static final int DECLARE = 5;
  public static final int LBRC = 39;
  public static final int EQL = 62;
  public static final int LE = 65;
  public static final int ELSEIF = 15;
  public static final int THEN = 27;
  public static final int DBLCLN = 35;
  public static final int FORTYPE = 29;
  public static final int LSCALEDOWN = 57;
  public static final int MOD = 47;
  public static final int FOLLOWSFROM = 72;
  public static final int RBRC = 40;
  public static final int INCLUDE = 2;
  public static final int PIPE = 43;
  public static final int DEFTYPE = 7;
  public static final int PLUS = 44;
  public static final int LPAR = 37;
  public static final int WHILE = 18;
  public static final int DECIMAL = 75;
  public static final int ASSIGN = 20;
  public static final int BOOLEAN = 73;
  public static final int DIMINV = 60;
  public static final int DO = 19;
  public static final int QUESTIONMARKS = 78;
  public static final int DEFCONV = 11;
  public static final int DIV = 46;
  public static final int PUBLIC = 12;
  public static final int RETURN = 28;
  public static final int MULT = 45;
  public static final int MDIV = 52;
  public static final int ELSE = 14;
  public static final int RSCALEDOWN = 55;
  public static final int EOF = 0;
  public static final int SEMICOLON = 34;
  public static final int RPAR = 38;
  public static final int DEFMATRIX = 9;
  public static final int IMPORT = 3;
  public static final int GTQ = 68;
  public static final int RECI = 61;
  public static final int IN = 24;
  public static final int HAT = 49;
  public static final int OR = 70;
  public static final int error = 1;
  public static final int MLEFTDIV = 54;
  public static final int EXCL = 21;
  public static final int LEFTDIV = 51;
  public static final int IF = 13;
  public static final int END = 17;
  public static final int COLON = 33;
  public static final int FORUNIT = 30;
  public static final int DEFALIAS = 10;
  public static final int PER = 26;
  public static final int DEFINDEX = 6;
  public static final int FORINDEX = 31;
  public static final int BEGIN = 16;
  public static final int DEFUNIT = 8;
  public static final int STRING = 77;
  public static final int NEQ = 63;
  public static final int AND = 69;
  public static final int IMPLIES = 71;
  public static final int TO = 22;
  public static final int LET = 25;
  public static final int NEG = 50;
  public static final int LEQ = 67;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INCLUDE",
  "IMPORT",
  "DEFINE",
  "DECLARE",
  "DEFINDEX",
  "DEFTYPE",
  "DEFUNIT",
  "DEFMATRIX",
  "DEFALIAS",
  "DEFCONV",
  "PUBLIC",
  "IF",
  "ELSE",
  "ELSEIF",
  "BEGIN",
  "END",
  "WHILE",
  "DO",
  "ASSIGN",
  "EXCL",
  "TO",
  "FROM",
  "IN",
  "LET",
  "PER",
  "THEN",
  "RETURN",
  "FORTYPE",
  "FORUNIT",
  "FORINDEX",
  "AT",
  "COLON",
  "SEMICOLON",
  "DBLCLN",
  "COMMA",
  "LPAR",
  "RPAR",
  "LBRC",
  "RBRC",
  "LBRACK",
  "RBRACK",
  "PIPE",
  "PLUS",
  "MULT",
  "DIV",
  "MOD",
  "MMULT",
  "HAT",
  "NEG",
  "LEFTDIV",
  "MDIV",
  "MEXPT",
  "MLEFTDIV",
  "RSCALEDOWN",
  "RSCALE",
  "LSCALEDOWN",
  "LSCALE",
  "TRANS",
  "DIMINV",
  "RECI",
  "EQL",
  "NEQ",
  "EQUIV",
  "LE",
  "GT",
  "LEQ",
  "GTQ",
  "AND",
  "OR",
  "IMPLIES",
  "FOLLOWSFROM",
  "BOOLEAN",
  "NATURAL",
  "DECIMAL",
  "IDENTIFIER",
  "STRING",
  "QUESTIONMARKS"
  };
}

