
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pacioli.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AT = 34;
  public static final int IDENTIFIER = 78;
  public static final int FROM = 24;
  public static final int GT = 68;
  public static final int TYPE = 21;
  public static final int NATURAL = 76;
  public static final int LAMBDA = 30;
  public static final int RSCALE = 58;
  public static final int EQUIV = 66;
  public static final int RBRACK = 44;
  public static final int TRANS = 61;
  public static final int COMMA = 38;
  public static final int LSCALE = 60;
  public static final int DEFINE = 4;
  public static final int LBRACK = 43;
  public static final int DECLARE = 5;
  public static final int LBRC = 41;
  public static final int EQL = 64;
  public static final int LE = 67;
  public static final int THEN = 28;
  public static final int DBLCLN = 37;
  public static final int FORTYPE = 31;
  public static final int LSCALEDOWN = 59;
  public static final int MOD = 49;
  public static final int FOLLOWSFROM = 74;
  public static final int RBRC = 42;
  public static final int INCLUDE = 3;
  public static final int PIPE = 45;
  public static final int DEFTYPE = 7;
  public static final int PLUS = 46;
  public static final int LPAR = 39;
  public static final int WHILE = 18;
  public static final int MODULE = 2;
  public static final int DECIMAL = 77;
  public static final int ASSIGN = 20;
  public static final int BOOLEAN = 75;
  public static final int DIMINV = 62;
  public static final int DO = 19;
  public static final int LDIV = 53;
  public static final int DOTDIV = 54;
  public static final int DEFCONV = 11;
  public static final int DIV = 48;
  public static final int PUBLIC = 13;
  public static final int RETURN = 29;
  public static final int MULT = 47;
  public static final int ELSE = 15;
  public static final int DOT = 50;
  public static final int RSCALEDOWN = 57;
  public static final int EOF = 0;
  public static final int SEMICOLON = 36;
  public static final int RPAR = 40;
  public static final int DEFMATRIX = 9;
  public static final int GTQ = 70;
  public static final int DEFPROJ = 12;
  public static final int RECI = 63;
  public static final int DOTHAT = 55;
  public static final int IN = 25;
  public static final int OR = 72;
  public static final int HAT = 51;
  public static final int error = 1;
  public static final int EXCL = 22;
  public static final int IF = 14;
  public static final int END = 17;
  public static final int COLON = 35;
  public static final int FORUNIT = 32;
  public static final int DEFALIAS = 10;
  public static final int PER = 27;
  public static final int DEFINDEX = 6;
  public static final int FORINDEX = 33;
  public static final int BEGIN = 16;
  public static final int DEFUNIT = 8;
  public static final int DOTLDIV = 56;
  public static final int STRING = 79;
  public static final int NEQ = 65;
  public static final int AND = 71;
  public static final int IMPLIES = 73;
  public static final int TO = 23;
  public static final int LET = 26;
  public static final int NEG = 52;
  public static final int LEQ = 69;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MODULE",
  "INCLUDE",
  "DEFINE",
  "DECLARE",
  "DEFINDEX",
  "DEFTYPE",
  "DEFUNIT",
  "DEFMATRIX",
  "DEFALIAS",
  "DEFCONV",
  "DEFPROJ",
  "PUBLIC",
  "IF",
  "ELSE",
  "BEGIN",
  "END",
  "WHILE",
  "DO",
  "ASSIGN",
  "TYPE",
  "EXCL",
  "TO",
  "FROM",
  "IN",
  "LET",
  "PER",
  "THEN",
  "RETURN",
  "LAMBDA",
  "FORTYPE",
  "FORUNIT",
  "FORINDEX",
  "AT",
  "COLON",
  "SEMICOLON",
  "DBLCLN",
  "COMMA",
  "LPAR",
  "RPAR",
  "LBRC",
  "RBRC",
  "LBRACK",
  "RBRACK",
  "PIPE",
  "PLUS",
  "MULT",
  "DIV",
  "MOD",
  "DOT",
  "HAT",
  "NEG",
  "LDIV",
  "DOTDIV",
  "DOTHAT",
  "DOTLDIV",
  "RSCALEDOWN",
  "RSCALE",
  "LSCALEDOWN",
  "LSCALE",
  "TRANS",
  "DIMINV",
  "RECI",
  "EQL",
  "NEQ",
  "EQUIV",
  "LE",
  "GT",
  "LEQ",
  "GTQ",
  "AND",
  "OR",
  "IMPLIES",
  "FOLLOWSFROM",
  "BOOLEAN",
  "NATURAL",
  "DECIMAL",
  "IDENTIFIER",
  "STRING"
  };
}

