
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package mvm.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int UNIT_EXPT = 34;
  public static final int SHAPE_UNOP = 38;
  public static final int MULT = 10;
  public static final int LITERAL_MATRIX = 42;
  public static final int CONST = 22;
  public static final int STR = 44;
  public static final int LOAD = 16;
  public static final int STORE = 17;
  public static final int NATURAL = 46;
  public static final int PATH = 28;
  public static final int UNIT = 13;
  public static final int BANG_SHAPE = 33;
  public static final int MATRIX = 30;
  public static final int SCALED_UNIT = 32;
  public static final int INDEXSET = 14;
  public static final int SEMICOLON = 3;
  public static final int RPAR = 7;
  public static final int BANG = 24;
  public static final int COMMA = 5;
  public static final int DIV = 11;
  public static final int APPLICATION = 19;
  public static final int UNITVECTOR = 15;
  public static final int BASEUNIT = 12;
  public static final int IF = 23;
  public static final int DECIMAL = 45;
  public static final int EOF = 0;
  public static final int LAMBDA = 20;
  public static final int error = 1;
  public static final int HAT = 8;
  public static final int SHAPE_BINOP = 39;
  public static final int REQUIRE = 2;
  public static final int IDENT = 43;
  public static final int SCALAR_SHAPE = 37;
  public static final int APPLICATION_DEBUG = 27;
  public static final int COLON = 4;
  public static final int NEG = 9;
  public static final int INDEX = 31;
  public static final int MATRIX_CONSTRUCTOR = 41;
  public static final int LIST = 29;
  public static final int LPAR = 6;
  public static final int STRING = 26;
  public static final int KEY = 25;
  public static final int UNIT_DIV = 36;
  public static final int SHAPE_EXPT = 40;
  public static final int UNIT_MULT = 35;
  public static final int VAR = 21;
  public static final int PRINT = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "REQUIRE",
  "SEMICOLON",
  "COLON",
  "COMMA",
  "LPAR",
  "RPAR",
  "HAT",
  "NEG",
  "MULT",
  "DIV",
  "BASEUNIT",
  "UNIT",
  "INDEXSET",
  "UNITVECTOR",
  "LOAD",
  "STORE",
  "PRINT",
  "APPLICATION",
  "LAMBDA",
  "VAR",
  "CONST",
  "IF",
  "BANG",
  "KEY",
  "STRING",
  "APPLICATION_DEBUG",
  "PATH",
  "LIST",
  "MATRIX",
  "INDEX",
  "SCALED_UNIT",
  "BANG_SHAPE",
  "UNIT_EXPT",
  "UNIT_MULT",
  "UNIT_DIV",
  "SCALAR_SHAPE",
  "SHAPE_UNOP",
  "SHAPE_BINOP",
  "SHAPE_EXPT",
  "MATRIX_CONSTRUCTOR",
  "LITERAL_MATRIX",
  "IDENT",
  "STR",
  "DECIMAL",
  "NATURAL"
  };
}

